### ISSUE TITLE
Radings of ADXL362 on Atmega1284P

### ISSUE THREAD

**Issue by jbrepogmailcom** [annem/ADXL362#7]
Dear sir/madam,

I have build arduino from Atmega1284P chip with 16MHz clock based on Arduino Uno*Pro. Readings from ADXL362 are kind of strange. Basic reading examples only show readings for axis X no mather how I tilt the sensor. No Y, Z or temp readings, just zeros. And readings for X are only values as 16,8,4,32,192,144,64, nothing else. Register 29 sometimes shows C0, sometimes 80. From that I suspect there could be timing problem with reading values through SPI. Have you tested examples on Atmega1284P?

Thanks, Jan

**Comment by jbrepogmailcom** [comment]
After some testing, I guess bad bit readings were caused by contact resistance. After rewiring the prototype the sensor works better.

**Comment by annem** [comment]
Jan,

Thanks so much for the update.  I'm so glad to hear it wasn't an issue with the library.  

I don't believe I have tested this library on an Atmega1284P...  does the library appear to be working correctly with it?

-Anne

**Comment by jbrepogmailcom** [comment]
Hello Anne,

unfortunately I was happy too early. I saw that all three axis are getting values, so I thought it is OK. But the values vary greatly, from -30000 to +30000 in two consecutive reading. Interestingly the X readings are quite stable, while Y and Z readings seem to be just random numbers. I was trying to read registers in both burst and one-by-one mode. Did not help.

The SPI library works fine, I am using it for work with SD card and ADXL362 library is just application of specific values to SPI library. So I have no idea what can be wrong. I think it is some timing.

Also when I connect Chip Select pin to ground, the ADXL362 sends all zeros.. I think it should not be like that.

Thanks, Jan
