### ISSUE TITLE
Only get XVALUE

### ISSUE THREAD

**Issue by noble1master** [annem/ADXL362#8]
Hello Sir,
I have a problem using your library with Sparkfun ADXL362 break out. When I run SimpleRead I only get XVALUE. Sample is pasted below... Please help.

Start Demo: Simple Read
XVALUE=0	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=192	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=128	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=252	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=254	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=128	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=0	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=0	YVALUE=0	ZVALUE=0	TEMPERATURE=0
XVALUE=0	YVALUE=0	ZVALUE=0	TEMPERATURE=0

**Comment by noble1master** [comment]
I did a lot to resolve issue. Now program works fine with this library. The problem is that the breakout seems not supporting 3 feet wire distance in between arduino and the breakout.

**Comment by itavero** [comment]
I think that really depends on the wiring and the speed you are using.
I have seen SPI connections over greater lengths.
You do need to be aware of the noise the wiring can pick up along the way and how this can affect the signal.
